### ISSUE TITLE
Building with Spack on Ubuntu 22.04 fails to install elfutils-0.186

### ISSUE THREAD

**Issue by pfmclaug** [dyninst/dyninst#1288]
Trying to install dyninst with spack on a fairly fresh Ubuntu 22.04 install using the following `.spack/linux/compilers.yml`:

```
- compiler:                                                                     
    spec: gcc@11.2.0                                                            
    paths:                                                                      
      cc: /usr/bin/gcc                                                          
      cxx: /usr/bin/g++                                                         
      f77: /usr/bin/gfortran                                                    
      fc: /usr/bin/gfortran                                                     
    flags: {}                                                                   
    operating_system: ubuntu22.04                                               
    target: x86_64                                                              
    modules: []                                                                 
    environment: {}                                                             
    extra_rpaths: [] 
```

The spack fails to build with:

```
==> Installing elfutils-0.186-npqyzhmxgxjjpor5d5feby7loauayf2i
...
==> elfutils: Executing phase: 'autoreconf'
==> elfutils: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/tmp/pfmclaug/spack-stage/spack-stage-elfutils-0.186-npqyzhmxgxjjpor5d5feby7loauayf2i/spack-src/configure' '--prefix=/scratch/software/omnitrace/spack/opt/spack/linux-ubuntu22.04-cascadelake/gcc-11.2.0/elfutils-0.186-npqyzhmxgxjjpor5d5feby7loauayf2i' '--without-bzlib' '--without-lzma' '--with-zlib=/scratch/software/omnitrace/spack/opt/spack/linux-ubuntu22.04-cascadelake/gcc-11.2.0/zlib-1.2.12-7vt7zzwb2s2js4o5jy7axtspzoku3h3m' 'LDFLAGS=-Wl,--no-as-needed -L/usr/lib -lintl' '--disable-debuginfod' '--disable-libdebuginfod'

2 errors found in build log:
     12    checking whether make supports nested variables... (cached) yes
     13    checking build system type... x86_64-pc-linux-gnu
     14    checking host system type... x86_64-pc-linux-gnu
     15    checking whether make supports the include directive... yes (GNU style)
     16    checking for gcc... /scratch/software/omnitrace/spack/lib/spack/env/gcc/gcc
     17    checking whether the C compiler works... no
  >> 18    configure: error: in `/tmp/pfmclaug/spack-stage/spack-stage-elfutils-0.186-npqyzhmxgxjjpor5d5feby7loauayf2i/spack-src':
  >> 19    configure: error: C compiler cannot create executables
     20    See `config.log' for more details
     See build log for details:
  /tmp/pfmclaug/spack-stage/spack-stage-elfutils-0.186-npqyzhmxgxjjpor5d5feby7loauayf2i/spack-build-out.txt
```

With the following spack-build-out.txt file:   
```
==> elfutils: Executing phase: 'autoreconf'                                     
==> elfutils: Executing phase: 'configure'                                      
==> [2022-07-26-12:48:14.163256] '/tmp/pfmclaug/spack-stage/spack-stage-elfutils-0.186-npqyzhmxgxjjpor5d5feby7loauayf2i/spack-src/configure' '--prefix=/scratch/software/omnitrace/spac
configure: No --program-prefix given, using "eu-"                               
checking for a BSD-compatible install... /usr/bin/install -c                    
checking whether build environment is sane... yes                               
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p                        
checking for gawk... gawk                                                       
checking whether make sets $(MAKE)... yes                                       
checking whether make supports nested variables... yes                          
checking whether to enable maintainer-specific portions of Makefiles... no      
checking whether make supports nested variables... (cached) yes                 
checking build system type... x86_64-pc-linux-gnu                               
checking host system type... x86_64-pc-linux-gnu                                
checking whether make supports the include directive... yes (GNU style)         
checking for gcc... /scratch/software/omnitrace/spack/lib/spack/env/gcc/gcc     
checking whether the C compiler works... no                                     
configure: error: in `/tmp/pfmclaug/spack-stage/spack-stage-elfutils-0.186-npqyzhmxgxjjpor5d5feby7loauayf2i/spack-src':
configure: error: C compiler cannot create executables                          
See `config.log' for more details    
 ```

**Comment by hainest** [comment]
>checking whether the C compiler works... no

This is a spack problem. What is the output of `spack compiler list`?

**Comment by pfmclaug** [comment]
> 
```
==> Available compilers
-- gcc ubuntu22.04-x86_64 ---------------------------------------
gcc@11.2.0
```

**Comment by pfmclaug** [comment]
I have partially found a way around it but there still seems to be an issue.

So I originally started with the following instructions:

```
spack compiler find
spack external find --all --not-buildable
spack spec -I --reuse dyninst
spack install --reuse dyninst
spack load -r dyninst
```

But once I removed all of the externals and had a clean spack folder I was able to `spack install dyninst` with no issues.

**Comment by hainest** [comment]
> But once I removed all of the externals and had a clean spack folder I was able to spack install dyninst with no issues.

I'm curious if there was a caching issue.

>spack external find --all --not-buildable

What's in your packages.yml?

**Comment by pfmclaug** [comment]
```
packages:
  autoconf:
    externals:
    - spec: autoconf@2.71
      prefix: /usr
    buildable: false
  automake:
    externals:
    - spec: automake@1.16.5
      prefix: /usr
    buildable: false
  bash:
    externals:
    - spec: bash@5.1.16
      prefix: /usr
    buildable: false
  berkeley-db:
    externals:
    - spec: berkeley-db@5.3.28
      prefix: /usr
    buildable: false
  binutils:
    externals:
    - spec: binutils@2.38
      prefix: /usr
    buildable: false
  bzip2:
    externals:
    - spec: bzip2@1.0.8
      prefix: /usr
    buildable: false
  cmake:
    externals:
    - spec: cmake@3.22.1
      prefix: /usr
    buildable: false
  cpio:
    externals:
    - spec: cpio@2.13
      prefix: /usr
    buildable: false
  curl:
    externals:
    - spec: curl@7.81.0+gssapi+ldap+nghttp2
      prefix: /usr
    buildable: false
  diffutils:
    externals:
    - spec: diffutils@3.8
      prefix: /usr
    buildable: false
  doxygen:
    externals:
    - spec: doxygen@1.9.1~graphviz~mscgen
      prefix: /usr
    buildable: false
  file:
    externals:
    - spec: file@5.41
      prefix: /usr
    buildable: false
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
    buildable: false
  gawk:
    externals:
    - spec: gawk@5.1.0
      prefix: /usr
    buildable: false
  gcc:
    externals:
    - spec: gcc@11.2.0 languages=c,c++,fortran
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/x86_64-linux-gnu-gcc-11
          cxx: /usr/bin/x86_64-linux-gnu-g++-11
          fortran: /usr/bin/x86_64-linux-gnu-gfortran-11
    buildable: false
  gettext:
    externals:
    - spec: gettext@0.21
      prefix: /usr
    buildable: false
  ghostscript:
    externals:
    - spec: ghostscript@9.55.0
      prefix: /usr
    buildable: false
  git:
    externals:
    - spec: git@2.34.1~tcltk
      prefix: /usr
    buildable: false
  gmake:
    externals:
    - spec: gmake@4.3
      prefix: /usr
    buildable: false
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
    buildable: false
  libfuse:
    externals:
    - spec: libfuse@3.10.5
      prefix: /usr
    buildable: false
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
    buildable: false
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
    buildable: false
  openmpi:
    externals:
    - spec: openmpi@4.1.2%gcc@11.2.0~cuda+cxx~cxx_exceptions+java~memchecker+pmi~static~wrapper-rpath
        fabrics=ofi,psm,psm2,ucx schedulers=slurm
      prefix: /usr
    buildable: false
  openssh:
    externals:
    - spec: openssh@8.9p1
      prefix: /usr
    buildable: false
  openssl:
    externals:
    - spec: openssl@3.0.2
      prefix: /usr
    buildable: false
  perl:
    externals:
    - spec: perl@5.34.0~cpanm+shared+threads
      prefix: /usr
    buildable: false
  python:
    externals:
    - spec: python@3.10.4+bz2+ctypes+dbm+ensurepip+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
    buildable: false
  rsync:
    externals:
    - spec: rsync@3.2.3
      prefix: /usr
    buildable: false
  ruby:
    externals:
    - spec: ruby@3.0.2
      prefix: /usr
    buildable: false
  sed:
    externals:
    - spec: sed@4.8
      prefix: /usr
    buildable: false
  subversion:
    externals:
    - spec: subversion@1.14.1
      prefix: /usr
    buildable: false
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
    buildable: false
  texinfo:
    externals:
    - spec: texinfo@6.8
      prefix: /usr
    buildable: false
  xz:
    externals:
    - spec: xz@5.2.5
      prefix: /usr
    buildable: false
  zip:
    externals:
    - spec: zip@3.0
      prefix: /usr
    buildable: false

```
